//marks card//
#include<iostream>
using namespace std;
int main()
{
    cout<< "****************************************************\n";
    cout<< "             CITY ENGINEERING COLLAGE               \n";
    cout<< "****************************************************\n";
    cout<< "      NAME:DHANUSHREE                 year:202\n";
    cout<< "      BRANCH:ISE                      sem:2nd\n";
    cout<< "****************************************************\n";
    cout<<   "mark1:   89\n";
    cout<<   "mark2:   89\n";
    cout<<   "mark3:   78\n";
    cout<<   "mark4:   90\n";
    cout<<   "mark5:   78\n";
    cout<<"*******************************************************\n";
    cout<<   "total:   424\n";
    cout<<   "avaerage:  84\n";
    cout<<   "grade:     'A'\n";
    cout<< "******************************************************\n";
    return 0;    
}